import { notFound } from 'next/navigation';
import { unstable_setRequestLocale } from 'next-intl/server';
import { isLocale, locales, type Locale } from '@/lib/i18n/config';
import { Breadcrumb } from '@/components/ui/Breadcrumb';
import { EntityHeader } from '@/components/ui/EntityHeader';

type Params = { locale: string };

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const COPY: Record<Locale, { title: string; sections: { heading: string; body: string }[] }> = {
  en: {
    title: 'Methodology',
    sections: [
      {
        heading: 'Scope',
        body: 'Cadastre catalogues publicly available data on land tenure, property markets, cadastral systems, and the built environment across African countries. Country is a top-level routing dimension; the schema is continental, not country-shaped.'
      },
      {
        heading: 'Provenance',
        body: 'Every dataset has a registry entry stating publisher, license, fetch method, fetch path, processed path, update frequency, and last-fetched timestamp. Every chart cites its dataset; every entity page provides BibTeX, APA, and Chicago citations.'
      },
      {
        heading: 'Languages',
        body: 'French is canonical for legal corpus. English and French are otherwise both first-class. Pages are sourced separately per language; translations are not regenerated by machine.'
      },
      {
        heading: 'Content schemas',
        body: 'Country, City, Quarter, Legal concept, Glossary term, and Dataset entities each have a strict YAML frontmatter schema validated at build time. A build that contains malformed frontmatter fails.'
      },
      {
        heading: 'Data pipeline',
        body: 'Raw source files live in data/raw/ and are never modified. ETL scripts in data/scripts/ are idempotent, respect robots.txt, and emit a manifest.json next to each output. Builds fail if a "live" dataset is older than its freshness window.'
      },
      {
        heading: 'Limits',
        body: 'Cadastre does not invent figures. Where a dataset is pending ingestion, the corresponding chart renders a placeholder noting that data is not yet available. The transaction registry contributed by partners is anonymised before any aggregation reaches a public surface.'
      }
    ]
  },
  fr: {
    title: 'Méthodologie',
    sections: [
      {
        heading: 'Périmètre',
        body: 'Cadastre catalogue des données publiques sur le foncier, les marchés immobiliers, les systèmes cadastraux et le cadre bâti dans les pays africains. Le pays est une dimension de routage de premier niveau ; le schéma est continental, non centré sur un pays.'
      },
      {
        heading: 'Provenance',
        body: 'Chaque jeu de données dispose d’une fiche indiquant l’éditeur, la licence, la méthode de collecte, le chemin de collecte, le chemin du fichier traité, la fréquence de mise à jour et la date de dernière collecte. Chaque graphique cite son jeu de données ; chaque page d’entité fournit des citations BibTeX, APA et Chicago.'
      },
      {
        heading: 'Langues',
        body: 'Le français fait foi pour le corpus juridique. Anglais et français sont par ailleurs tous deux de premier rang. Les pages sont rédigées séparément dans chaque langue ; les traductions ne sont pas régénérées par machine.'
      },
      {
        heading: 'Schémas de contenu',
        body: 'Pays, Ville, Quartier, Notion juridique, Terme du glossaire et Jeu de données disposent chacun d’un schéma YAML strict validé à la compilation. Une compilation contenant un en-tête mal formé échoue.'
      },
      {
        heading: 'Pipeline de données',
        body: 'Les fichiers sources bruts résident dans data/raw/ et ne sont jamais modifiés. Les scripts ETL de data/scripts/ sont idempotents, respectent robots.txt et écrivent un manifest.json à côté de chaque sortie. La compilation échoue si un jeu « publié » dépasse sa fenêtre de fraîcheur.'
      },
      {
        heading: 'Limites',
        body: 'Cadastre n’invente pas de chiffres. Lorsqu’un jeu de données est en attente d’intégration, le graphique correspondant affiche un repère indiquant que les données ne sont pas encore disponibles. Le registre des transactions transmis par des partenaires est anonymisé avant toute agrégation rendue publique.'
      }
    ]
  }
};

export default async function MethodologyPage({ params }: { params: Params }) {
  if (!isLocale(params.locale)) notFound();
  unstable_setRequestLocale(params.locale);
  const locale = params.locale as Locale;
  const copy = COPY[locale];
  return (
    <div className="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8 pb-16">
      <div className="pt-6">
        <Breadcrumb locale={locale} items={[{ label: copy.title }]} />
      </div>
      <EntityHeader kicker="Cadastre" title={copy.title} locale={locale} />
      <article className="flex flex-col gap-10 max-w-3xl">
        {copy.sections.map((s, i) => (
          <section key={i}>
            <h2 className="text-lg font-medium mb-2">{s.heading}</h2>
            <p className="text-base text-ink-primary leading-relaxed">{s.body}</p>
          </section>
        ))}
      </article>
    </div>
  );
}
